//
// Generated file, do not edit! Created by nedtool 5.6 from TerryMsg.msg.
//

#ifndef __TERRYMSG_M_H
#define __TERRYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TerryMsg.msg:16</tt> by nedtool.
 * <pre>
 * packet TerryMsg
 * {
 *     int sequenceNumber;
 *     int Creado = false;
 *     int origin;
 *     string ruta;
 * }
 * </pre>
 */
class TerryMsg : public ::omnetpp::cPacket
{
  protected:
    int sequenceNumber;
    int Creado;
    int origin;
    ::omnetpp::opp_string ruta;

  private:
    void copy(const TerryMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TerryMsg&);

  public:
    TerryMsg(const char *name=nullptr, short kind=0);
    TerryMsg(const TerryMsg& other);
    virtual ~TerryMsg();
    TerryMsg& operator=(const TerryMsg& other);
    virtual TerryMsg *dup() const override {return new TerryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getCreado() const;
    virtual void setCreado(int Creado);
    virtual int getOrigin() const;
    virtual void setOrigin(int origin);
    virtual const char * getRuta() const;
    virtual void setRuta(const char * ruta);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TerryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TerryMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TERRYMSG_M_H

